version: '3.8'

services:
  dependency-track:
    image: dependencytrack/apiserver:latest
    container_name: dependency-track-apiserver
    ports:
      - "8080:8080"
    volumes:
      - ./app/data:/data
      - ./app/logs:/var/log/dependency-track
    environment:
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://postgres:5432/dependencytrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=dependencytrack
      - ALPINE_DATABASE_PASSWORD=dependencytrack
    depends_on:
      - postgres
    restart: unless-stopped

  dependency-track-frontend:
    image: dependencytrack/frontend:latest
    container_name: dependency-track-frontend
    ports:
      - "8081:8080"
    environment:
      - API_BASE_URL=http://localhost:8080
    depends_on:
      - dependency-track
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: dependency-track-postgres
    environment:
      - POSTGRES_DB=dependencytrack
      - POSTGRES_USER=dependencytrack
      - POSTGRES_PASSWORD=dependencytrack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
